[package]
name = "auth-server-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version ="1.0.144", features = ["derive"] }
rocket_okapi = "0.8.0-rc.2"